### ISSUE TITLE
Readme is outdated

### ISSUE THREAD

**Issue by Flakebi** [NixOS/nixops#1285]
Hi,
I just tried to build nixops like described in the readme, with `nix-build release.nix -A build.x86_64-linux` but it failed:
```
error: attribute 'build' in selection path 'build.x86_64-linux' not found
```

45d4049 seems to have changed it to `nix-build release.nix -A nixops.x86_64-linux`.

**Comment by adisbladis** [comment]
This is upated in https://github.com/NixOS/nixops/pull/1284

**Comment by adisbladis** [comment]
Oh, and if you just want to build for your current architecture you can simply:
`nix-build default.nix`

**Comment by grahamc** [comment]
I merged #1284 but we should add some docs to the readme on making a poetry environment for development time. For what it was worth, this is how I do it:

pyproject.toml:

```toml
[tool.poetry]
name = "nixopsenv"
version = "0.1.0"
description = ""
authors = [ "graham@grahamc.com" ]

[tool.poetry.dependencies]
python = "^3.7"
nixops = {git = "https://github.com/grahamc/nixops.git", rev = "integration"}
nixops-packet = {git = "https://github.com/grahamc/nixops-packet.git", rev = "poetry"}
#nixops = { path = "../../github.com/NixOS/nixops" }
#nixopspacket = {path = "../../github.com/input-output-hk/nixops-packet"}

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
```

then:

```
$ nix-shell -p poetry
[nix-shell]$ poetry lock
[nix-shell]$ poetry install
[nix-shell]$ poetry shell
[poetry-shell]$ nixops ...
```
